apiVersion: v1
kind: Pod
metadata:
  name: rook-ceph-osd-cache-drop
  # for openshift, namespace is openshift-storage
  # for upstream K8S, namespace is rook-ceph
  namespace: {{ rook_ceph_namespace }}
  # this yaml leaves namespace blank so that it works for
  # either one if user specifies namespace correctly
spec:
  containers:
  - name: rook-ceph-osd-cache-drop
    image: quay.io/cloud-bulldozer/ceph-cache-dropper:latest
    imagePullPolicy: Always
    command: [/bin/sh, -c]
    args:
      - cd /opt/snafu/ceph-cache-dropper; python3 ./osd-cache-drop-websvc.py
    env:
      - name: ROOK_CEPH_TOOLBOX_POD
        value: {{ rook_ceph_toolbox_pod }}
      - name: ROOK_CEPH_NAMESPACE
        value: {{ rook_ceph_namespace }}
